django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

django_store/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('account/profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProductListView.as_view(), name='store-home'),
    path('seller/<str:username>', views.SellerProductListView.as_view(), name='seller-home'),
    path('seller/<str:username>/followers/add/', views.AddFollowerView.as_view(), name='add_follower'),
    path('seller/<str:username>/followers/remove/', views.RemoveFollowerView.as_view(), name='remove_follower'),
    path('product/new', views.ProductCreateView.as_view(), name='product-create'),
    path('product/search', views.product_search, name='product-search'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/update', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
]

store/models.py
from operator import mod
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    price = models.FloatField(default=0)
    stock = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_pics')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        output_size = (500, 500)
        img.thumbnail(output_size)
        img.save(self.image.path)


class Rating(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    rate = models.IntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)


class CartItem(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(default=timezone.now)

store/forms.py
from django import forms
from .models import ProductImage


class ProductImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image', widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = ProductImage
        fields = ['image']

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from store.forms import ProductImageForm
from .models import Product, ProductImage, Rating


class ProductListView(ListView):
    model = Product
    template_name = 'store/home.html'
    context_object_name = 'products'
    ordering = ['-created_at']

    def get_context_data(self, **kwargs):
        context =  super(ProductListView, self).get_context_data(**kwargs)
        context.update({
        })
        return context


class SellerProductListView(ListView):
    model = Product
    template_name = 'store/seller_products.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        seller = get_object_or_404(User, username=self.kwargs.get('username'))
        followers = seller.profile.followers.all()
        is_following = False
        for follower in followers:
            if follower == self.request.user:
                is_following = True
                break
            else:
                is_following = False
        follower_no = len(followers)
        context = super(SellerProductListView, self).get_context_data(**kwargs)
        context.update({
            'follower_no': follower_no,
            'is_following': is_following,
        })
        return context

    def get_queryset(self):
        seller = get_object_or_404(User, username=self.kwargs.get('username'))
        return Product.objects.filter(seller=seller).order_by('-created_at')


class ProductDetailView(DetailView):
    model = Product
    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        product = Product.objects.get(pk=pk)
        product_images = ProductImage.objects.filter(product=product)
        ratings = Rating.objects.filter(product=product)
        rating_no = len(ratings)
        followers = product.seller.profile.followers.all()
        follower_no = len(followers)
        products = Product.objects.filter(seller=product.seller)
        product_no = len(products)
        ratings_no = sum([sum([rating.rate for rating in rating_list]) for rating_list in [Rating.objects.filter(product=prod) for prod in products]])
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context.update({
            'product_images': product_images,
            'ratings': ratings,
            'rating_no': rating_no,
            'ratings_no': ratings_no,
            'product_no': product_no,
            'follower_no': follower_no
        })
        return context



class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['name', 'brand', 'category', 'price', 'stock', 'description']

    def get_context_data(self, **kwargs):
        image_form = ProductImageForm()
        context =  super(ProductCreateView, self).get_context_data(**kwargs)
        context.update({
            "image_form": image_form
        })
        return context

    def form_valid(self, form):
        form.instance.seller = self.request.user
        super().form_valid(form)
        files = self.request.FILES.getlist('image')
        for file in files:
            ProductImage.objects.create(product=form.instance, image=file)
        return redirect('product-detail', pk=form.instance.pk)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    fields = ['name', 'brand', 'category', 'price', 'stock', 'description']

    def get_context_data(self, **kwargs):
        image_form = ProductImageForm()
        context =  super(ProductUpdateView, self).get_context_data(**kwargs)
        context.update({
            "image_form": image_form
        })
        return context

    def form_valid(self, form):
        form.instance.seller = self.request.user
        super().form_valid(form)
        files = self.request.FILES.getlist('image')
        for file in files:
            ProductImage.objects.create(product=form.instance, image=file)
        return redirect('product-detail', pk=form.instance.pk)

    def test_func(self):
        product = self.get_object()
        return self.request.user == product.seller


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = '/'

    def test_func(self):
        product = self.get_object()
        return self.request.user == product.seller


class AddFollowerView(LoginRequiredMixin, View):
    def post(self, request, username, *args, **kwargs):
        user = User.objects.get(username=username)
        user.profile.followers.add(request.user)

        return redirect('seller-home', username=user.username)


class RemoveFollowerView(LoginRequiredMixin, View):
    def post(self, request, username, *args, **kwargs):
        user = User.objects.get(username=username)
        user.profile.followers.remove(request.user)

        return redirect('seller-home', username=user.username)


def product_search(request):
    if request.method == "POST":
        search = request.POST.get('search')
        products = Product.objects.filter(name__contains=search)
        context = {
            'search': search,
            'products': products,
        }
        return render(request, 'store/product_search.html', context=context)
    else:
        return render(request, 'store/product_search.html', {})

store/templates/store/about.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>About</h1>
{% endblock content %}

store/templates/store/carousel.html
{% load static %}
<div
  id="carouselExampleInterval"
  class="carousel slide"
  data-bs-ride="carousel"
>
<div class="carousel-indicators">
  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" aria-label="Slide 1" class="active" aria-current="true"></button>
  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
</div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="6000">
      <img src="{% static 'store/src/ads/landing.png' %}" class="d-block w-100" alt="..." />
    </div>
    <div class="carousel-item" data-bs-interval="6000">
      <img src="{% static 'store/src/ads/landing.png' %}" class="d-block w-100" alt="..." />
    </div>
    <div class="carousel-item" data-bs-interval="6000">
      <img src="{% static 'store/src/ads/landing.png' %}" class="d-block w-100" alt="..." />
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleInterval"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleInterval"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

store/templates/store/categories.html
{% load static %}
<div class="container-fluid mt-4 pt-3 bg-white px-0">
  <h5 class="ms-3 mb-3">CATEGORIES</h5>
  <div class="d-flex flex-wrap">
    {% for _ in '1234567812345678'|make_list %}
    <div class="card rounded-0" style="width: 12.499999995%">
        <img src="{% static 'store/src/cats/mobile.jpeg' %}" class="card-img-top" alt="Mobile & Gadgets">
        <div class="card-body text-center">
            <p class="card-text">Mobile & Gadgets</p>
        </div>
    </div>
    {% endfor %}
  </div>
</div>

store/templates/store/discover.html
{% load static %}
<div class="container-fluid mt-4 px-0">
    <div class="bg-white">
        <h5 class="ms-3 mb-3 py-3">DISCOVER</h5>
    </div>
    <div class="d-flex flex-wrap mb-2">
        {% for product in products %}
        <div class="col-2 my-1">
            <a class="card mx-1 text-decoration-none h-100" href="{% url 'product-detail' product.id %}">
                <div class="card-body text-center pb-1 text-dark">
                    <img src="{{ product.productimage_set.all.0.image.url }}" class="card-img-top" alt="Mobile & Gadgets">
                    <p class="card-text small">{{ product.name }}</p>
                </div>
                <div class="px-2">
                    <small class="btn btn-outline-success px-1 py-0" style="font-size: calc(1em - 5px);">Support Local</small>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center bg-white border-0 small">
                    <span class="text-success price">{{ product.price }}</span>
                    <span class="text-muted">{{ product.sold }} sold</span>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <!-- <div class="col-12 d-flex justify-content-center">
        <a href="" class="btn btn-secondary my-3 px-4 py-2">Load More</a>
    </div> -->
</div>

store/templates/store/home.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
{% include 'store/landing.html' %}
<!-- {% include 'store/categories.html' %} -->
<div class="py-3 bg-light"></div>
{% include 'store/discover.html' %}
{% endblock content %}

store/templates/store/landing.html
{% load static %}
<div
  id="carouselExampleInterval"
  class="carousel slide"
  data-bs-ride="carousel"
>
<div class="carousel-indicators">
  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" aria-label="Slide 1" class="active" aria-current="true"></button>
  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
</div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="6000">
      <img src="{% static 'store/src/ads/landing.png' %}" class="d-block w-100" alt="..." />
    </div>
    <div class="carousel-item" data-bs-interval="6000">
      <img src="{% static 'store/src/ads/landing.png' %}" class="d-block w-100" alt="..." />
    </div>
    <div class="carousel-item" data-bs-interval="6000">
      <img src="{% static 'store/src/ads/landing.png' %}" class="d-block w-100" alt="..." />
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleInterval"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleInterval"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

store/templates/store/product_confirm_delete.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="bg-white p-5 rounded border">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Product</legend>
            <h2>Are you sure you want to delete the product "{{ object.name }}"?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-secondary" href="{% url 'product-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %} 

store/templates/store/product_detail.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
<script defer src="{% static 'store/script/product_detail.js' %}"></script>
<div class="bg-white p-4">
    <div class="d-flex">
        <div class="col-4">
            <div id="playerbox">
                <img id="playerimg" class="w-100" src="{{ product_images.0.image.url }}" height="300">
            </div>
            <div class="d-flex mt-2 overflow-scroll">
                {% for image in product_images %}
                <div class="col-2 bg-white">
                    <img src="{{ image.image.url }}" alt="Profile Picture" class="w-100 product-image">
                </div>
                {% endfor %}
            </div>
            <div class="d-flex mt-3">
                <!-- <button type="button" class="col-6 d-flex btn btn-outline-primary justify-content-center" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <i class="bi bi-share me-2"></i>
                    <span>Share</span>
                </button> -->
                <button type="button" class="col-6 d-flex btn btn-outline-primary justify-content-center" id="liveToastBtn" onclick="copy(window.location.href)">
                    <i class="bi bi-share me-2"></i>
                    <span>Share</span>
                </button>
                <div class="toast-container position-fixed bottom-0 end-0 p-3">
                  <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header">
                        <!-- <div class="bg-primary p-1 rounded-circle me-1"></div> -->
                        <strong class="me-auto text-capitalize text-primary">
                            <i class="bi bi-share me-2"></i>
                            <span>Share</span>
                        </strong>
                        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                    <div class="toast-body">
                        Link has been copied to your clipboard.
                    </div>
                  </div>
                </div>   
           
                <div class="border-start"></div>
                <div class="col-6 d-flex btn btn-outline-danger justify-content-center">
                    <i class="bi bi-heart me-2"></i>
                    <span>Favourite</span>
                </div>
            </div>
        </div>
        <div class="col-8 p-4 d-flex flex-column">
            <h4>{{ object.name }}</h4>
            <div class="small d-flex ">
                <div class="text-success">
                    <span>5.0</span>
                    {% for _ in '12345'|make_list %}
                    <i class="bi bi-star-fill"></i>
                    {% endfor %}
                </div>
                <div class="border-start mx-1"></div>
                <div class="">
                    <span>{{ rating_no }} Ratings</span>
                </div>
                <div class="border-start mx-1"></div>
                <div class="">
                    <span>{{ object.sold }} Sold</span>
                </div>
            </div>
            <h1 class="price">{{ object.price }}</h1>
            <div class="d-flex">
                <div class="col-2">
                    <small>Shipping</small>
                </div>
                <div class="d-flex flex-column col-10">
                    <div class="d-flex">
                        <i class="bi bi-truck text-success me-2"></i>
                        <div class="col-8 d-flex justify-content-between">
                            <div class="col-4">
                                <small class="">Free Shipping</small>
                            </div>
                            <div class="col-4">
                                <div class=""></div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex">
                        <i class="bi bi-airplane me-2"></i>
                        <div class="d-flex flex-column col-8">
                            <div class="col-12 d-flex justify-content-between">
                                <div class="col-6">
                                    <small class="text-muted">Shipping From</small>
                                </div>
                                <div class="col-6">
                                    <small>Singapore</small>
                                </div>
                            </div>
                            <div class="col-12 d-flex justify-content-between">
                                <div class="col-6">
                                    <small class="text-muted">Shipping Fee</small>
                                </div>
                                <div class="col-6">
                                    <small>$0.00 - $1.00</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex mt-2 align-items-center">
                <div class="col-2">
                    <small>Quantity</small>
                </div>
                <!-- TODO: stick the input as a whole tgt -->
                <div class="d-flex align-items-center">
                    <div class="input-group d-flex mt-2">
                        <button class="input-group-text rounded-0" id="minus" onclick="minusQuantity()"><i class="bi bi-dash"></i></button>
                        <input 
                            type="text" class="form-control text-center w-25" id="quantity" value=0 
                            aria-label="quantity" aria-describedby="plus minus" 
                            oninput="checkQuantity()" onblur="checkQuantityNull()">
                        <button class="input-group-text rounded-0" id="plus" onclick="plusQuantity()"><i class="bi bi-plus"></i></button>
                    </div>
                    <span class="text-muted col-6 ms-3 mt-1">{{ object.stock }} available</span>
                </div>
            </div>
            <div class="d-flex mt-4">
                <div class="btn btn-outline-success rounded-0">
                    <i class="bi bi-cart-plus mx-1"></i>
                    <span>Add to Cart</span>
                </div>
                <div class="btn btn-success rounded-0 ms-3">
                    <i class="bi bi-cart-check mx-1"></i>
                    <span>Buy Now</span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="bg-white mt-3 p-4 d-flex align-items-center">
    <div class="col-1">
        <img src="{{ object.seller.profile.image.url }}" alt="Profile Picture" class="w-100 rounded-circle border">
    </div>
    <div class="col-4 ps-3 d-flex flex-column border-end">
        <span>{{ object.seller }}</span>
        <small class="text-muted">Active 20 minutes ago</small>
        <div class="d-block mt-1">
            <a href="" class="btn btn-outline-success">
                <i class="bi bi-chat-left-text"></i>
                <span>Chat Now</span>
            </a>
            <a href="{% url 'seller-home' object.seller.username %}" class="btn btn-outline-secondary">
                <i class="bi bi-shop"></i>
                <span>View Seller</span>
            </a>
        </div>
    </div>
    <div class="col-7 ps-4 small">
        <div class="d-flex my-2">
            <div class="col-3">
                <span>Ratings</span>
                <span class="text-success">{{ ratings_no }}</span>
            </div>
            <div class="col-5">
                <span>Response Rate</span>
                <span class="text-success">100%</span>
            </div>
            <div class="col-4">
                <span>Joined</span>
                <span class="text-success">{{ object.seller.date_joined|timesince  }}</span>
            </div>
        </div>
        <div class="d-flex my-1">
            <div class="col-3">
                <span>Products</span>
                <span class="text-success">{{ product_no }}</span>
            </div>
            <div class="col-5">
                <span>Response Time</span>
                <span class="text-success">within hours</span>
            </div>
            <div class="col-4">
                <span>Follower</span>
                <span class="text-success">{{ follower_no }}</span>
            </div>
        </div>
    </div>
</div>
<div class="bg-white mt-5 py-2 px-2">
    <div class="container">
        <div class="bg-light px-3 pt-3 pb-1 my-4">
            <h6>Product Specifications</h6>
        </div>
        <div class="small mx-2">
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Category</span>
                </div>
                <div class="col">
                    <span>{{ object.category }}</span>
                </div>
            </div>
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Brand</span>
                </div>
                <div class="col">
                    <span>{{ object.brand }}</span>
                </div>
            </div>
            <!-- <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Warranty Type</span>
                </div>
                <div class="col">
                    <span>Supplier Warranty</span>
                </div>
            </div>
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Wireless</span>
                </div>
                <div class="col">
                    <span>Yes</span>
                </div>
            </div>
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Mobile Cable Type</span>
                </div>
                <div class="col">
                    <span>Lightning, Type C</span>
                </div>
            </div>
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Safety Mark</span>
                </div>
                <div class="col">
                    <span>CCC FCC</span>
                </div>
            </div> -->
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Stock</span>
                </div>
                <div class="col">
                    <span>{{ object.stock }}</span>
                </div>
            </div>
            <div class="d-flex">
                <div class="col-2">
                    <span class="text-muted">Ships From</span>
                </div>
                <div class="col">
                    <span>Singapore</span>
                </div>
            </div>
        </div>
        <div class="bg-light px-3 pt-3 pb-1 my-4">
            <h6>Product Description</h6>
        </div>
        <div class="small mx-2">
            <p>{{ object.description }}</p>
        </div>
    </div>
</div>
{% endblock content %}

store/templates/store/product_form.html
{% extends 'includes/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="bg-white p-5 rounded border">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Product</legend>
            {{ form|crispy }}
            {{ image_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-success" type="submit">Create</button>
        </div>
    </form>
</div>
{% endblock content %} 

store/templates/store/product_search.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
{% if search %}
<div class="container-fluid mt-4 px-0">
    <div class="bg-white">
        <h5 class="ms-3 mb-3 py-3">RESULT FOR "<span class="text-success">{{ search }}</span>"</h5>
    </div>
    <div class="d-flex flex-wrap mb-2">
        {% for product in products %}
        <div class="col-2 my-1">
            <a class="card mx-1 text-decoration-none h-100" href="{% url 'product-detail' product.id %}">
                <div class="card-body text-center pb-1 text-dark">
                    <img src="{% static 'store/src/disc/wireless.jpeg' %}" class="card-img-top" alt="Mobile & Gadgets">
                    <p class="card-text small">{{ product.name }}</p>
                </div>
                <div class="px-2">
                    <small class="btn btn-outline-success px-1 py-0" style="font-size: calc(1em - 5px);">Support Local</small>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center bg-white border-0 small">
                    <span class="text-success price">{{ product.price }}</span>
                    <span class="text-muted">{{ product.sold }} sold</span>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <!-- <div class="col-12 d-flex justify-content-center">
        <a href="" class="btn btn-secondary my-3 px-4 py-2">Load More</a>
    </div> -->
</div>
{% else %}
    <h1>Hey! You forget to search for a product...</h1>
{% endif %}
{% endblock content %}

store/templates/store/shop_products.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
{% include 'store/landing.html' %}
{% include 'store/categories.html' %}
<div class="py-3 bg-light"></div>
{% include 'store/discover.html' %}
{% endblock content %}